### ISSUE TITLE
[BUG] Cannot acess unsafe website

### ISSUE THREAD

**Issue by gustavfaustino** [fmhy/FMHY-SafeGuard#15]
### Describe the bug

I know I shouldn't go to unsafe websites, but when I try to access filecr (marked as unsafe, i know ) to check some files there, when I click "Continue" the page reloads and sends me to the warning again, infinitely.

### Steps to Reproduce

1. Acess file.cr;
2. The warning message will apear
3. Click on Proceed
4. Click on Yes, to proceed
5. Then the website load and the same warning message, over and over

### Expected behavior

It is expected that, even if it is not safe, I will be able to enter if I want to.

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.

**Comment by kenhendricks00** [comment]
Thanks for reporting this! I identified the issue that caused the warning loop when trying to proceed to unsafe sites like file.cr, and it’s now been fixed and will be released in the latest update. You should be able to continue to the site if you choose to, without getting stuck in the loop. Please update to the latest version of FMHY SafeGuard when it releases, and let us know if you run into any further issues. We appreciate your patience and your help in improving the extension!

**Comment by gustavfaustino** [comment]
Thanks! It's working, and without loops! Keep up the great work!
