### ISSUE TITLE
[BUG] No data for subdirectories of websites

### ISSUE THREAD

**Issue by mrrpmrreeoow** [fmhy/FMHY-SafeGuard#2]
### Describe the bug

![image](https://github.com/user-attachments/assets/e823c92e-8a9c-4333-8f5a-558f80b6a400)
![image](https://github.com/user-attachments/assets/cea78607-6ca1-428a-bba8-ca6900c1ebca)

### Steps to Reproduce

1. Open a safe (or even unsafe) site
2. You will get a rating
3. Go to a subdirectory of a website
4. "No data available for https://listedsite.example/subdirectory"

### Expected behavior

It should show ratings for all subdirectories (and probably also all subdomains) of listed websites

### FMHY SafeGuard Version

1.0.4

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.

**Comment by kenhendricks00** [comment]
Hi MIOGMIOG,

Thank you for submitting this bug report and providing detailed reproduction steps. We have addressed the issue you highlighted in the [latest version (v1.0.5)](https://github.com/kenhendricks00/FMHY-SafeGuard/releases/tag/v1.0.5).

The extension now correctly identifies subdirectories and applies the proper rating for safe, starred, unsafe, or potentially unsafe sites. This means that any subdirectory of a listed site will reflect the correct status, ensuring consistency across both the main domains and their subdirectories, as you expected. Subdomains will also be recognized, improving the reliability of the status checks.

We appreciate your patience and feedback, making FMHY SafeGuard better for everyone.

Thanks again!

Best,
Ken
