### ISSUE TITLE
Chromium Extension?

### ISSUE THREAD

**Issue by ghost** [fmhy/FMHY-SafeGuard#3]
### Is your feature request related to a problem? Please describe.

No.

### Describe the solution you'd like

Hello, I was wondering if you guys will ever add a chromium extension. I want it because I am currently using Chrome and can't really switch to Firefox overnight.

**Comment by kenhendricks00** [comment]
Hi kvhjdffv,

Thanks so much for reaching out and sharing your feature request!

We heard you, and we're excited to let you know that we have now created a Chrome version of the FMHY SafeGuard extension! We are currently undergoing review to be put on the Chrome Web Store, but you can still manually use it via the [v1.0.5 release page](https://github.com/kenhendricks00/FMHY-SafeGuard/releases/tag/v1.0.5).

We hope this makes your browsing experience even better. Please feel free to reach out if you have any questions or feedback about the Chrome version.

Thanks again for your suggestion—it really helps us improve!

Best,
Ken
