### ISSUE TITLE
 https://github.com/yoshiask/FluentStore?tab=readme-ov-file [BUG] (and other sites)

### ISSUE THREAD

**Issue by githlacker** [fmhy/FMHY-SafeGuard#7]
### Describe the bug

i was trying the extension on FluentStore site and it worked at first but after only going backward then forward in the page it stopped working and didn't put it as a starred site (this is happening in most sites)

### Steps to Reproduce

going backward and forward in the page

### Expected behavior

stops starring the stared site

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.

**Comment by kenhendricks00** [comment]
Hi githlacker,

The behavior you’re experiencing—where the star indicator is removed after navigating back and forth on certain pages—is related to how the extension currently recognizes URLs. Right now, anything after the main domain path (such as query parameters like ?tab=readme-ov-file) isn't being consistently recognized, which causes the star indicator to disappear on subpages or URLs with extra parameters.

I’ll address this in the next update by refining the URL matching logic to recognize subpages and queries within the same domain properly. This should ensure the starred status remains consistent across navigation.

Thanks again for your input, and stay tuned for the fix!

**Comment by kenhendricks00** [comment]
Hi githlacker, just a quick update: this bug has been addressed in the latest update!

The URL matching logic has been refined, so the star indicator should now remain consistent across subpages and URLs with additional parameters within the same domain. Please update to the latest version, and let us know if you encounter any further issues.

Thank you for helping us improve FMHY SafeGuard!
