### ISSUE TITLE
Consistent Starred Site Indicator for Subpages? 

### ISSUE THREAD

**Issue by githlacker** [fmhy/FMHY-SafeGuard#8]
### Is your feature request related to a problem? Please describe.

Hello, just saying i really appreciate the extension and what yall doing. However, i've noticed that the star indicator disappears when navigating to subpages, like for example moving from `https://steamrip.com/` to `https://steamrip.com/crackedgame` stops being starred

so asking if it would be possible to add a feature that could maintain the starred site indicator across all subpages within a trusted domain? (this would make it easier to recognize and navigate safe sites consistently tbh)

### Describe the solution you'd like

A way to keep the extension starring the site even after entering a subpage of the starred domain

**Comment by kenhendricks00** [comment]
Hello githlacker, thank you for the feedback and for supporting the project!

We appreciate you bringing this up. The behavior you've described—where the star indicator disappears when navigating to subpages—was indeed an issue in previous versions. However, this was addressed in v1.0.5 ([release notes here](https://github.com/kenhendricks00/FMHY-SafeGuard/releases/tag/v1.0.5)), which introduced a fix for maintaining the starred indicator across subpages of trusted domains.

If you’re still experiencing this issue, please ensure that you’re running version 1.0.5 or later. If you’re already on the latest version and this behavior persists, feel free to let us know, and we’ll investigate further.

Thanks again for the support and for helping make this extension better!

**Comment by githlacker** [comment]
Hello kenh,

I wanted to extend my thanks for addressing the issue with the indicator, And i also like to report that it’s now working perfectly 

I’ve tested the feature on Firefox as well as brave browser and the starred indicator is maintaining its functionality across both platforms

Thank you for your hard work on this project and for your quick response

**Comment by kenhendricks00** [comment]
Thank you so much for your kind words! :)
