### ISSUE TITLE
[BUG] Write a title for your bug

### ISSUE THREAD

**Issue by frickypickle** [fmhy/FMHY-SafeGuard#9]
### Describe the bug

Unable to install latest version of plugin on firefox

### Steps to Reproduce

1. go to releases and try to download the file
2. it will not install and an error will popup:
![image](https://github.com/user-attachments/assets/27ca6b14-69bf-418f-a46c-9ebab67775bb)

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.

**Comment by kenhendricks00** [comment]
Hi eclipsek20, thanks for reaching out!

I’ve addressed the installation issue and released an updated, signed version of the extension that should resolve the error you encountered on Firefox. You can download the new version from the [latest release](https://github.com/kenhendricks00/FMHY-SafeGuard/releases/tag/v1.0.9).

Please give it a try and let us know if you encounter any further issues. Thanks for helping improve FMHY SafeGuard!
